version: '3.9'

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    volumes:
      - type: volume
        source: neo4j-data
        target: /data
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_default__database=literature-graph

volumes:
  neo4j-data:
